title: "CSCI 182: Fall 2022"
subtitle: "Introduction to Programming: Media Applications"
email: vanwars@unca.edu
baseurl: "/fall2022"
term_start_date: "2022-08-15"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
campuswire_url: https://campuswire.com/c/G7DE56EF3/feed

timezone: "America/New_York"
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude: 
  - _lectures/draft
  - _assignments/draft
  - course-files/administrative
  - course-files/build
  - course-files/exams
  - course-files/homework/drafts
  - course-files/tutorials/drafts
  - course-files/lectures/drafts
  - course-files/practice_exams/drafts
  - course-files/projects/drafts
collections:
  assignments:
    output: true
    sort_by: ordering
    permalink: /assignments/:name
  lectures:
    output: true
    sort_by: lecture_date
    permalink: /lectures/:name

collections_dir: pages

sass:
  style: compact
  sass_dir: _sass

deadline_reminder: false


